# Site settings
title: Jorge Figueiredo
email: blog@jorgefigueiredo.com
description: > # this means to ignore newlines until "baseurl:"
  Computer Science, Big Data, Cloud and Machine Learning
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jorgefigueiredo.com" # the base hostname & protocol for your site
twitter_username: jorgeacf
github_username:  jorgeacf

# Build settings
markdown: kramdown

#highlighter: pygments # pygments or rouge

